name: ğŸ„ Advent of Code Download Input ğŸ„
on:
  workflow_dispatch:
jobs:
  build:
    name: â¬‡ï¸ Download Input Files â¬‡ï¸
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'alasdairnicol') # don't run in forks
    steps:
      - uses: actions/checkout@v2
      - name: run download script
        with:
          session: ${{ secrets.AOC_SESSION }}
          year: 2021
        run: |
          python .github/workflows/download_input_files
      - uses: joblo2213/aoc-badges-action@v3.0.0
      - name: ğŸ“¤ Push
        run: |
          git config --global user.email "<>"
          git config --global user.name "AOC README Bot ğŸ¤–"
          git add *.txt
          git diff-index --quiet HEAD || git commit --message "Downloaded Input Files"
          git push
